name: Build and tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout respository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci
        name: Install modules from npm

      - run: npm run build
        name: Build the application

  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout respository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci
        name: Install modules from npm

      - run: npm test
        name: Run the tests

  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout respository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci
        name: Install modules from npm

      - run: npm test -- --coverage
        name: Run tests coverage

      - uses: actions/upload-artifact@v4
        name: Archive coverage report
        with:
          name: coverage-report
          path: coverage
